org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.builtInKotlin=true
android.skipBuildDependencyValidation=true
android-skip-build-dependency-validation=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
